[project]
name = "vlarl-launcher"
version = "0.1.0"
description = ""
authors = [
    {name = "chenhao lu",email = "luch21@mails.tsinghua.edu.cn"}
]
readme = "README.md"
requires-python = ">=3.10,<3.14"
dependencies = [
    "websockets (>=15.0.1,<16.0.0)",
    "tyro (>=0.9.32,<0.10.0)",
    "torch (>=2.8.0,<3.0.0)",
    "safetensors (>=0.6.2,<0.7.0)",
    "packaging (>=25.0,<26.0)",
    "python-dateutil (>=2.9.0.post0,<3.0.0)",
    "pyyaml (>=6.0.3,<7.0.0)",
    "swanlab (>=0.6.10,<0.7.0)",
    "wandb (>=0.22.0,<0.23.0)",
    "vlarl-client @ git+ssh://git@github.com/CTP314/vlarl-client.git",
    "tensordict (>=0.10.0,<0.11.0)",
    "ray (>=2.51.1,<3.0.0)",
]

[tool.poetry.scripts]
vlarl-run-server = "vlarl_launcher.cli:main"
vlarl-run-server-ray = "vlarl_launcher.cli_ray:main"

[tool.poetry.group.dppo.dependencies]
dppo = {git = "git@github.com:CTP314/dppo.git"}



[tool.poetry.group.reinflow.dependencies]
reinflow = {git = "git@github.com:CTP314/ReinFlow.git"}

[[tool.poetry.source]]
name = "mirrors"
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"
priority = "primary"

[tool.poetry]
packages = [{include = "vlarl_launcher", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
